/**
 *   \file config_macro.h
 *   \brief 一些可修改的通用配置宏
 */

#ifndef _CONFIG_MACRO_H_
#define _CONFIG_MACRO_H_


#define MAX_UART_NUM 4 /* 最大串口 */
#define MAX_DEV_NUM 256 /* 最大装置数量 */
#define MAX_MODEL_NUM 32 /* 最大模板数 */

#define PROTOCOL_NUM 16
#define PROTOCOL_BUF_LEN 512

#define COMM_NUM 4
#define COMM_DATA_NUM 4 /* 最大通讯行 */
#define COMM_DEV_NUM 256 /* 每个通讯行最大装置数 */

#define UART_RECV_TIMEOUT 10000 /* 最大等待时间毫秒 */

/* #define DEV_YC_DATA_NUM 128 /\* 装置最大遥测数量 *\/ */
/* #define DEV_YX_DATA_NUM 64 /\* 装置最大遥信数量 *\/ */
/* #define DEV_YM_DATA_NUM 32 /\* 装置最大遥信数量 *\/ */
#define DEV_TYPE_DATA_NUM 256 /* 装置最大遥测数量 */

#define TOPOLOGICAL_DEV_MAX_CHILD_NUM 32 /* 拓扑下最多子节点数量 */

/* 模块数据类型 */
typedef enum _MODEL_DATA_TYPE
{
	MODEL_DATA_TYPE_NULL = 0,
	MODEL_DATA_TYPE_YC,
	MODEL_DATA_TYPE_YX,
	MODEL_DATA_TYPE_YM,
	MODEL_DATA_TYPE_EIT300 = 100,
	MODEL_DATA_TYPE_EM600C96,
	MODEL_DATA_TYPE_EIT300S_HUM_TMP,
	MODEL_DATA_TYPE_EIT300S_HUM_TMP_DI_STATE,
	MODEL_DATA_TYPE_EIT300E_12T,
	MODEL_DATA_TYPE_EIT300E_12T_SOE,
	MODEL_DATA_TYPE_EVENT_RECORD = 200,
	MODEL_AUTOUP_YX=300,
	MODEL_DATA_TYPE_CYCLE_END = 999 ,

	MODEL_DATA_TYPE_YK = 1000,
	MODEL_DATA_TYPE_PARAM = 1100,

	MODEL_DATA_TYPE_FROZEN_INSTANT = 2000,
	MODEL_DATA_TYPE_FROZEN_MIN,
	MODEL_DATA_TYPE_FROZEN_HOUR,
	MODEL_DATA_TYPE_FROZEN_DAY,
	MODEL_DATA_TYPE_FROZEN_MONTH,
	MODEL_DATA_TYPE_FROZEN_YEAR,

	MODEL_DATA_TYPE_FROZEN_CFG_INSTANT = 2030,
	MODEL_DATA_TYPE_FROZEN_CFG_MIN,
	MODEL_DATA_TYPE_FROZEN_CFG_HOUR,
	MODEL_DATA_TYPE_FROZEN_CFG_DAY,
	MODEL_DATA_TYPE_FROZEN_CFG_MONTH,
	MODEL_DATA_TYPE_FROZEN_CFG_YEAR,

	MODEL_DATA_TYPE_FROZEN_OTHER_BLOCK_MIN_BEGIN = 2060,
	MODEL_DATA_TYPE_FROZEN_OTHER_BLOCK_MIN_END = 2069,

	MODEL_TIME_SYNC = 2100,
	MODEL_MODBUS_EIT300E_12T_TIME_SYNC = 2101,
	MODEL_TIME_SYNC_END = 2120,

	MODEL_EVENT_AUTOUP = 2130,
	MODEL_AUTOUP_RESET ,
	MODEL_AUTOUP_SET ,

	MODEL_EVENT_RECORD_PROTECT_ACT=2200,
	MODEL_EVENT_RECORD_PROTECT_MODE,
	MODEL_EVENT_RECORD_BRAKE,
	MODEL_EVENT_RECORD_ALARM,

	MODEL_EVENT_RECORD_CFG=2230,
	/* MODEL_EVENT_RECORD_CFG_PROTECT_MODE, */
	/* MODEL_EVENT_RECORD_CFG_BRAKE, */
	/* MODEL_EVENT_RECORD_CFG_ALARM, */
	/* MODEL_EVENT_RECORD_CFG_POWER, */
	/* MODEL_EVENT_RECORD_CFG_DI, */

	MODEL_TOPOLOGICAL_CLEAR_RECORD = 3000,
	MODEL_TOPOLOGICAL_SEND_CURRENT,
	MODEL_TOPOLOGICAL_RECV_CURRENT,
	MODEL_TOPOLOGICAL_SEND_WATING,

}MODEL_DATA_TYPE;

#define TOPOLOGICAL_JSON_FILE "/data/app/gw1376.2/topological_result.json"
#define TOPOLOGICAL_JSON_DIR "/data/app/topolocal/result/"
#define TOPOLOGICAL_JSON_NUM (128)
#define BREAKER_COMM_STATE_FILE "/data/app/breaker/comm_state.log"
#define BREAKER_CONF_DIR "/data/app/breaker/configFile"

#endif /* _CONFIG_MACRO_H_ */
